#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

# powerline symbol ''

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    leading_diamond = ''
    template = '{{.Icon}} '
    background = 'p:frappe_magenta'
    foreground = 'p:text'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .Path }}'
    background = 'p:macchiato_orange'
    foreground = 'p:text'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .HEAD }}'
    background = 'p:blue'
    foreground = 'p:text'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[palette]
  blue = '#8AADF4'
  lavender = '#B7BDF8'
  orange = '#fab387'
  os = '#ACB0BE'
  pink = '#F5BDE6'
  text = '#494D64'
  wight = '#FFFFFF'

  # catppuccin-frappe colors
  frappe_bg="#303446"
  frappe_fg="#c6d0f5"
  frappe_cyan="#99d1db"
  frappe_black="#292c3c"
  frappe_gray="#414559"
  frappe_magenta="#ca9ee6"
  frappe_pink="#f4b8e4"
  frappe_red="#e78284"
  frappe_green="#a6d189"
  frappe_yellow="#e5c890"
  frappe_blue="#8caaee"
  frappe_orange="#ef9f76"
  frappe_black4="#626880"

  # catppuccin-latte colors
  latte_bg="#eff1f5"
  latte_fg="#4c4f69"
  latte_cyan="#04a5e5"
  latte_black="#e6e9ef"
  latte_gray="#ccd0da"
  latte_magenta="#8839ef"
  latte_pink="#ea76cb"
  latte_red="#d20f39"
  latte_green="#40a02b"
  latte_yellow="#df8e1d"
  latte_blue="#1e66f5"
  latte_orange="#fe640b"
  latte_black4="#acb0be"

  # macchiato colors
  macchiato_bg="#24273a"
  macchiato_fg="#cad3f5"
  macchiato_cyan="#91d7e3"
  macchiato_black="#1e2030"
  macchiato_gray="#363a4f"
  macchiato_magenta="#c6a0f6"
  macchiato_pink="#f5bde6"
  macchiato_red="#ed8796"
  macchiato_green="#a6da95"
  macchiato_yellow="#eed49f"
  macchiato_blue="#8aadf4"
  macchiato_orange="#f5a97f"
  macchiato_black4="#5b6078"

  # mocha colors
  mocha_bg="#1e1e2e"
  mocha_fg="#cdd6f4"
  mocha_cyan="#89dceb"
  mocha_black="#181825"
  mocha_gray="#313244"
  mocha_magenta="#cba6f7"
  mocha_pink="#f5c2e7"
  mocha_red="#f38ba8"
  mocha_green="#a6e3a1"
  mocha_yellow="#f9e2af"
  mocha_blue="#89b4fa"
  mocha_orange="#fab387"
  mocha_black4="#585b70"
